import Head from 'next/head'


const first = () => {
  return (
    <>
        <Head>
            <title>Project Quadverse</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1>My first Next Page</h1>
        </main>
    </>
  )
}

export default first
